// creating an array and passing the number, questions, options and answers

let questions = [
  {
    numb: 1,
    question: "What is the capital of France?",
    answer: "Paris",
    options: ["London", "Paris", "Berlin", "Madrid"],
  },
  {
    numb: 2,
    question: "Which animal is known as the King of the Jungle?",
    answer: "Lion",
    options: ["Elephant", "Lion", "Tiger", "Giraffe"],
  },
  {
    numb: 3,
    question: "What color is the sky on a clear day?",
    answer: "Blue",
    options: ["Green", "Blue", "Red", "Yellow"],
  },
  {
    numb: 4,
    question: "How many legs does a spider have?",
    answer: "Eight",
    options: ["Six", "Eight", "Ten", "Four"],
  },
  {
    numb: 5,
    question: "Which planet is known as the Red Planet?",
    answer: "Mars",
    options: ["Earth", "Mars", "Jupiter", "Venus"],
  },
  {
    numb: 6,
    question: "What do bees produce?",
    answer: "Honey",
    options: ["Honey", "Milk", "Butter", "Sugar"],
  },
  {
    numb: 7,
    question: "How many days are in a week?",
    answer: "Seven",
    options: ["Five", "Seven", "Ten", "Four"],
  },
  {
    numb: 8,
    question: "Which fruit is known for keeping the doctor away?",
    answer: "Apple",
    options: ["Banana", "Apple", "Mango", "Orange"],
  },
  {
    numb: 9,
    question: "What is 2 + 2?",
    answer: "4",
    options: ["3", "4", "5", "6"],
  },
  {
    numb: 10,
    question: "Which gas do humans need to breathe?",
    answer: "Oxygen",
    options: ["Carbon dioxide", "Oxygen", "Helium", "Hydrogen"],
  },
  {
    numb: 11,
    question: "How many letters are in the English alphabet?",
    answer: "26",
    options: ["24", "25", "26", "27"],
  },
  {
    numb: 12,
    question: "Which season comes after summer?",
    answer: "Autumn",
    options: ["Winter", "Autumn", "Spring", "Monsoon"],
  },
  {
    numb: 13,
    question: "What is the opposite of hot?",
    answer: "Cold",
    options: ["Warm", "Cold", "Cool", "Heat"],
  },
  {
    numb: 14,
    question: "Which shape has four equal sides?",
    answer: "Square",
    options: ["Triangle", "Rectangle", "Square", "Circle"],
  },
  {
    numb: 15,
    question: "Which is the fastest land animal?",
    answer: "Cheetah",
    options: ["Cheetah", "Horse", "Kangaroo", "Elephant"],
  },
  {
    numb: 16,
    question: "What do cows drink?",
    answer: "Water",
    options: ["Water", "Milk", "Juice", "Soda"],
  },
  {
    numb: 17,
    question: "How many hours are in a day?",
    answer: "24",
    options: ["12", "24", "36", "48"],
  },
  {
    numb: 18,
    question: "Which part of the body helps us to see?",
    answer: "Eyes",
    options: ["Nose", "Eyes", "Ears", "Mouth"],
  },
  {
    numb: 19,
    question: "Which is the largest ocean on Earth?",
    answer: "Pacific",
    options: ["Atlantic", "Indian", "Arctic", "Pacific"],
  },
  {
    numb: 20,
    question: "Which number comes after 9?",
    answer: "10",
    options: ["8", "10", "11", "12"],
  },
  {
    numb: 21,
    question: "What is the color of grass?",
    answer: "Green",
    options: ["Green", "Blue", "Red", "Yellow"],
  },
  {
    numb: 22,
    question: "Which animal barks?",
    answer: "Dog",
    options: ["Cat", "Dog", "Cow", "Horse"],
  },
  {
    numb: 23,
    question: "How many fingers do humans have on one hand?",
    answer: "Five",
    options: ["Three", "Four", "Five", "Six"],
  },
  {
    numb: 24,
    question: "Which of these is a fruit?",
    answer: "Banana",
    options: ["Carrot", "Potato", "Banana", "Lettuce"],
  },
  {
    numb: 25,
    question: "What do we use to write on paper?",
    answer: "Pencil",
    options: ["Spoon", "Pencil", "Eraser", "Plate"],
  },
  {
    numb: 26,
    question: "Which month comes after April?",
    answer: "May",
    options: ["March", "May", "June", "July"],
  },
  {
    numb: 27,
    question: "What is the name of the planet we live on?",
    answer: "Earth",
    options: ["Mars", "Jupiter", "Earth", "Saturn"],
  },
  {
    numb: 28,
    question: "Which animal gives us milk?",
    answer: "Cow",
    options: ["Sheep", "Cow", "Dog", "Tiger"],
  },
  {
    numb: 29,
    question: "What is the main source of light during the day?",
    answer: "Sun",
    options: ["Moon", "Sun", "Stars", "Lamp"],
  },
  {
    numb: 30,
    question: "Which of these is used to tell time?",
    answer: "Clock",
    options: ["Chair", "Clock", "Shoe", "Book"],
  },
  {
    numb: 31,
    question: "How many wheels does a bicycle have?",
    answer: "Two",
    options: ["One", "Two", "Three", "Four"],
  },
  {
    numb: 32,
    question: "Which of these is a type of transportation?",
    answer: "Car",
    options: ["Car", "Chair", "Table", "Pencil"],
  },
  {
    numb: 33,
    question: "Which of these is a vegetable?",
    answer: "Tomato",
    options: ["Apple", "Tomato", "Grapes", "Mango"],
  },
  {
    numb: 34,
    question: "What do birds use to fly?",
    answer: "Wings",
    options: ["Legs", "Wings", "Fins", "Ears"],
  },
  {
    numb: 35,
    question: "Which of these is a mode of water transport?",
    answer: "Boat",
    options: ["Car", "Bicycle", "Boat", "Bus"],
  },
  {
    numb: 36,
    question: "Which shape is round?",
    answer: "Circle",
    options: ["Square", "Triangle", "Circle", "Rectangle"],
  },
  {
    numb: 37,
    question: "What is the color of a ripe banana?",
    answer: "Yellow",
    options: ["Green", "Red", "Yellow", "Blue"],
  },
  {
    numb: 38,
    question: "How many arms do humans have?",
    answer: "Two",
    options: ["One", "Two", "Three", "Four"],
  },
  {
    numb: 39,
    question: "Which of these is a pet?",
    answer: "Dog",
    options: ["Lion", "Elephant", "Dog", "Tiger"],
  },
  {
    numb: 40,
    question: "Which of these is a body part?",
    answer: "Hand",
    options: ["Table", "Chair", "Hand", "Door"],
  },
  {
    numb: 41,
    question: "What is the opposite of big?",
    answer: "Small",
    options: ["Small", "Tall", "Wide", "Heavy"],
  },
  {
    numb: 42,
    question: "Which of these is a drink?",
    answer: "Juice",
    options: ["Rice", "Juice", "Bread", "Soap"],
  },
  {
    numb: 43,
    question: "What do you wear on your feet?",
    answer: "Shoes",
    options: ["Hat", "Shoes", "Gloves", "Shirt"],
  },
  {
    numb: 44,
    question: "Which of these is a day of the week?",
    answer: "Monday",
    options: ["January", "Monday", "Winter", "Morning"],
  },
  {
    numb: 45,
    question: "What do we use to brush our teeth?",
    answer: "Toothbrush",
    options: ["Comb", "Toothbrush", "Spoon", "Soap"],
  },
  {
    numb: 46,
    question: "Which of these animals can fly?",
    answer: "Bird",
    options: ["Dog", "Elephant", "Bird", "Cat"],
  },
  {
    numb: 47,
    question: "What do we use to eat soup?",
    answer: "Spoon",
    options: ["Fork", "Spoon", "Knife", "Plate"],
  },
  {
    numb: 48,
    question: "Which of these is used to cut paper?",
    answer: "Scissors",
    options: ["Pen", "Scissors", "Eraser", "Ruler"],
  },
  {
    numb: 49,
    question: "What do we see in the sky at night?",
    answer: "Moon",
    options: ["Sun", "Moon", "Rainbow", "Clouds"],
  },
  {
    numb: 50,
    question: "Which of these is sweet?",
    answer: "Sugar",
    options: ["Sugar", "Salt", "Pepper", "Lemon"],
  },
];
