// creating an array and passing the number, questions, options and answers

let questions = [
  {
    numb: 1,
    question: "What is the capital of France?",
    answer: "Paris",
    options: ["Madrid", "Paris", "London", "Berlin"],
  },
  {
    numb: 2,
    question: "Which animal is known as the King of the Jungle?",
    answer: "Lion",
    options: ["Giraffe", "Tiger", "Elephant", "Lion"],
  },
  {
    numb: 3,
    question: "What color is the sky on a clear day?",
    answer: "Blue",
    options: ["Red", "Blue", "Green", "Yellow"],
  },
  {
    numb: 4,
    question: "How many legs does a spider have?",
    answer: "Eight",
    options: ["Ten", "Six", "Eight", "Four"],
  },
  {
    numb: 5,
    question: "Which planet is known as the Red Planet?",
    answer: "Mars",
    options: ["Jupiter", "Mars", "Earth", "Venus"],
  },
  {
    numb: 6,
    question: "What do bees produce?",
    answer: "Honey",
    options: ["Milk", "Honey", "Butter", "Sugar"],
  },
  {
    numb: 7,
    question: "How many days are in a week?",
    answer: "Seven",
    options: ["Four", "Seven", "Five", "Ten"],
  },
  {
    numb: 8,
    question: "Which fruit is known for keeping the doctor away?",
    answer: "Apple",
    options: ["Apple", "Orange", "Mango", "Banana"],
  },
  {
    numb: 9,
    question: "What is 2 + 2?",
    answer: "4",
    options: ["6", "3", "4", "5"],
  },
  {
    numb: 10,
    question: "Which gas do humans need to breathe?",
    answer: "Oxygen",
    options: ["Helium", "Oxygen", "Hydrogen", "Carbon dioxide"],
  },
  {
    numb: 11,
    question: "How many letters are in the English alphabet?",
    answer: "26",
    options: ["27", "24", "26", "25"],
  },
  {
    numb: 12,
    question: "Which season comes after summer?",
    answer: "Autumn",
    options: ["Winter", "Monsoon", "Spring", "Autumn"],
  },
  {
    numb: 13,
    question: "What is the opposite of hot?",
    answer: "Cold",
    options: ["Cold", "Heat", "Warm", "Cool"],
  },
  {
    numb: 14,
    question: "Which shape has four equal sides?",
    answer: "Square",
    options: ["Rectangle", "Triangle", "Square", "Circle"],
  },
  {
    numb: 15,
    question: "Which is the fastest land animal?",
    answer: "Cheetah",
    options: ["Horse", "Elephant", "Cheetah", "Kangaroo"],
  },
  {
    numb: 16,
    question: "What do cows drink?",
    answer: "Water",
    options: ["Soda", "Water", "Juice", "Milk"],
  },
  {
    numb: 17,
    question: "How many hours are in a day?",
    answer: "24",
    options: ["48", "24", "12", "36"],
  },
  {
    numb: 18,
    question: "Which part of the body helps us to see?",
    answer: "Eyes",
    options: ["Mouth", "Ears", "Nose", "Eyes"],
  },
  {
    numb: 19,
    question: "Which is the largest ocean on Earth?",
    answer: "Pacific",
    options: ["Arctic", "Pacific", "Atlantic", "Indian"],
  },
  {
    numb: 20,
    question: "Which number comes after 9?",
    answer: "10",
    options: ["8", "11", "10", "12"],
  },
  {
    numb: 21,
    question: "What is the color of grass?",
    answer: "Green",
    options: ["Yellow", "Green", "Blue", "Red"],
  },
  {
    numb: 22,
    question: "Which animal barks?",
    answer: "Dog",
    options: ["Dog", "Horse", "Cow", "Cat"],
  },
  {
    numb: 23,
    question: "How many fingers do humans have on one hand?",
    answer: "Five",
    options: ["Four", "Six", "Three", "Five"],
  },
  {
    numb: 24,
    question: "Which of these is a fruit?",
    answer: "Banana",
    options: ["Banana", "Lettuce", "Potato", "Carrot"],
  },
  {
    numb: 25,
    question: "What do we use to write on paper?",
    answer: "Pencil",
    options: ["Pencil", "Eraser", "Plate", "Spoon"],
  },
  {
    numb: 26,
    question: "Which month comes after April?",
    answer: "May",
    options: ["June", "May", "March", "July"],
  },
  {
    numb: 27,
    question: "What is the name of the planet we live on?",
    answer: "Earth",
    options: ["Earth", "Jupiter", "Mars", "Saturn"],
  },
  {
    numb: 28,
    question: "Which animal gives us milk?",
    answer: "Cow",
    options: ["Dog", "Tiger", "Sheep", "Cow"],
  },
  {
    numb: 29,
    question: "What is the main source of light during the day?",
    answer: "Sun",
    options: ["Sun", "Moon", "Stars", "Lamp"],
  },
  {
    numb: 30,
    question: "Which of these is used to tell time?",
    answer: "Clock",
    options: ["Shoe", "Chair", "Clock", "Book"],
  },
  {
    numb: 31,
    question: "How many wheels does a bicycle have?",
    answer: "Two",
    options: ["Two", "Four", "Three", "One"],
  },
  {
    numb: 32,
    question: "Which of these is a type of transportation?",
    answer: "Car",
    options: ["Chair", "Pencil", "Car", "Table"],
  },
  {
    numb: 33,
    question: "Which of these is a vegetable?",
    answer: "Tomato",
    options: ["Mango", "Apple", "Tomato", "Grapes"],
  },
  {
    numb: 34,
    question: "What do birds use to fly?",
    answer: "Wings",
    options: ["Ears", "Legs", "Wings", "Fins"],
  },
  {
    numb: 35,
    question: "Which of these is a mode of water transport?",
    answer: "Boat",
    options: ["Boat", "Bicycle", "Bus", "Car"],
  },
  {
    numb: 36,
    question: "Which shape is round?",
    answer: "Circle",
    options: ["Rectangle", "Triangle", "Square", "Circle"],
  },
  {
    numb: 37,
    question: "What is the color of a ripe banana?",
    answer: "Yellow",
    options: ["Blue", "Yellow", "Green", "Red"],
  },
  {
    numb: 38,
    question: "How many arms do humans have?",
    answer: "Two",
    options: ["One", "Three", "Two", "Four"],
  },
  {
    numb: 39,
    question: "Which of these is a pet?",
    answer: "Dog",
    options: ["Tiger", "Elephant", "Dog", "Lion"],
  },
  {
    numb: 40,
    question: "Which of these is a body part?",
    answer: "Hand",
    options: ["Chair", "Hand", "Door", "Table"],
  },
  {
    numb: 41,
    question: "What is the opposite of big?",
    answer: "Small",
    options: ["Wide", "Heavy", "Tall", "Small"],
  },
  {
    numb: 42,
    question: "Which of these is a drink?",
    answer: "Juice",
    options: ["Juice", "Soap", "Rice", "Bread"],
  },
  {
    numb: 43,
    question: "What do you wear on your feet?",
    answer: "Shoes",
    options: ["Shoes", "Shirt", "Hat", "Gloves"],
  },
  {
    numb: 44,
    question: "Which of these is a day of the week?",
    answer: "Monday",
    options: ["January", "Winter", "Monday", "Morning"],
  },
  {
    numb: 45,
    question: "What do we use to brush our teeth?",
    answer: "Toothbrush",
    options: ["Spoon", "Toothbrush", "Comb", "Soap"],
  },
  {
    numb: 46,
    question: "Which of these animals can fly?",
    answer: "Bird",
    options: ["Cat", "Dog", "Bird", "Elephant"],
  },
  {
    numb: 47,
    question: "What do we use to eat soup?",
    answer: "Spoon",
    options: ["Plate", "Fork", "Spoon", "Knife"],
  },
  {
    numb: 48,
    question: "Which of these is used to cut paper?",
    answer: "Scissors",
    options: ["Eraser", "Pen", "Ruler", "Scissors"],
  },
  {
    numb: 49,
    question: "What do we see in the sky at night?",
    answer: "Moon",
    options: ["Clouds", "Sun", "Rainbow", "Moon"],
  },
  {
    numb: 50,
    question: "Which of these is sweet?",
    answer: "Sugar",
    options: ["Sugar", "Pepper", "Lemon", "Salt"],
  },
];
